### ISSUE TITLE
Would be nice if you could add a list of OpenSource tools for WAFs

### ISSUE THREAD

**Issue by daknhh** [0xInfection/Awesome-WAF#17]
You could start eg with the https://github.com/globaldatanet/aws-firewall-factory

**Comment by 0xInfection** [comment]
There is already a tooling section: https://github.com/0xInfection/Awesome-WAF#awesome-tools

If you think the tool you've mentioned is security centric and belongs to one of the categories in there, feel free to create a PR. Cheers!
