### ISSUE TITLE
Add Google Cloud Platform WAF bypass with 8KB packet

### ISSUE THREAD

**Issue by PinkDev1** [0xInfection/Awesome-WAF#19]
https://kloudle.com/blog/piercing-the-cloud-armor-the-8kb-bypass-in-google-cloud-platform-waf

**Comment by 0xInfection** [comment]
Hi, thanks for linking this. I added a new section here: https://github.com/0xInfection/Awesome-WAF/blob/master/README.md#abuse-waf-limit-on-http-responses
