### ISSUE TITLE
Missing words?

### ISSUE THREAD

**Issue by simonamor** [0xInfection/Awesome-WAF#2]
https://github.com/0xInfection/Awesome-WAF/blob/7e0344bb7e6dabe0fbca85f4f2c9528c3a21f8ae/README.md#where-to-look

Where To Look:
    Always look out for common ports that expose that a WAF 80, 443, 8000, 8008, 8080, 8088.

Should this read something like ... expose that a WAF is present such as 80, ... ? How does taking screenshots help this?

**Comment by 0xInfection** [comment]
Most of the sites running a WAF usually have strict https rules, i.e. users are allowed to connect via port 443 only. Now when you're trying to access an open port, eg. 8080, the WAF will pull out a block page. The main target of this is to provoke the WAF and make it pull out its blocked page, hence we can identify what WAF it is via the fingerprints provided. 

Now coming to the tool I added in the tip, WebScreenShot can visit several ports and take a screenshot of the page on the port it visits. Now when it visits port 8080, the WAF pulls out the block page, the tool screenshots it and saves for us. Note later you can just open up the page it has saved and examine the fingerprint!
